### ISSUE TITLE
[Bug] missing item

### ISSUE THREAD

**Issue by Lead-Lord** [derfurkan/OfflinePlayers#10]
**Describe the bug**
I don't think the item drops when the monster kills the player.

**To Reproduce**
1. Kill an offline player by a monster

**Information to investigate**
- Server Version   1.19.4 
- Console logs   X
- Spigot or Bukkit   spigot
- Using a fork or original   pufferfish
- What plugins
- Which version of OfflinePlayers and LibsDisguises   2.4 / 10.0.36-Free
- #Welcome to OfflinePlayers
```
#This Plugin spawns a clone from a Player if he is offline at his logout location!
#Here you can configure the plugin and the behavior of the offline clones.

OfflinePlayer:
  cloneEntity: PLAYER #The entity type of the clone. You can find a list of all entity types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  cloneRawEntity: FOX #The raw entity type that will be used to create an undisguised clone. This entity will be disguised with the cloneEntity.
  cloneSpawnDistance: 100 #The range in blocks a player has to be in to show a clone.
  cloneUpdateTimer: 15 #The value in ticks that defines in which interval the clone's visible state is updated. (20 ticks = 1 second)
  cloneItemPickup: true #If true the clones will be able to pick up items.
  cloneIsHittable: true #If the clone is damageable.
  cloneHasAI: true #If true the clone is able to be fall down, pushed or knocked back.
  cloneCanProvoke: true #If true the clone can be targeted by mobs.
  cloneName: "§8§l오프라인 §7- §c%PLAYER_NAME" #The name of the clone. %PLAYER_NAME will be replaced with the name of the player. %DESPAWN_TIMER% will be replaced with the time until the clone despawns.
  cloneDe-spawnTimer:
    enabled: false
    timer: 20 #The time in seconds the clone is de-spawned after it is spawned.
  game-modeBlacklist: #A list of gamemodes where the clones will not spawn.
    - CREATIVE
    - SPECTATOR
  worldBlacklist: #A list of worlds where the clones will not spawn.
    - world1
    - world2
    - world3
    - test
  permissions: #If enabled players will only get a clone if they have the permission.
    enabled: false
    permission: 'offlineplayer.clone'
```
- etc. (Every bit of information that you might think is relevant in fixing the issue)
