### ISSUE TITLE
Foxes replaces player and doesnt despawn when player rejoins

### ISSUE THREAD

**Issue by J-dotjs** [derfurkan/OfflinePlayers#5]
Server Version: Spigot 1.19.4
Console logs: not relevant
Spigot or Bukkit: Spigot
Using a fork or original: Original
What plugins: BreakTogether, CropsPlus, DiscordChatMonitor, dualhorse, EnchantsSquared, Graves, LibsDisguises, mydog, OfflinePlayers, OldCOmbatMechanics, ProtocolLib, ValorlessUtils
Which version of OfflinePlayers and LibsDisguises: 2.2, 10.0.35
Your config.yml file: 
```
#Welcome to OfflinePlayers
#This Plugin spawns a clone from a Player if he is offline at his logout location!
#Here you can configure the plugin and the behavior of the offline clones.

OfflinePlayer:
  cloneEntity: PLAYER #The entity type of the clone. You can find a list of all entity types here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/entity/EntityType.html
  cloneRawEntity: FOX #The raw entity type that will be used to create an undisguised clone. This entity will be disguised with the cloneEntity.
  cloneSpawnDistance: 50 #The range in blocks a player has to be in to show a clone.
  cloneUpdateTimer: 15 #The value in ticks that defines in which interval the clone's visible state is updated. (20 ticks = 1 second)
  cloneItemPickup: true #If true the clones will be able to pick up items.
  cloneIsHittable: false #If the clone is damageable.
  cloneHasAI: true #If true the clone is able to be fall down, pushed or knocked back.
  cloneName: "§8§lOffline §7- §c%PLAYER_NAME" #The name of the clone. %PLAYER_NAME will be replaced with the name of the player. %DESPAWN_TIMER% will be replaced with the time until the clone despawns.
  cloneDe-spawnTimer:
    enabled: false
    timer: 20 #The time in seconds the clone is de-spawned after it is spawned.
  game-modeBlacklist: #A list of gamemodes where the clones will not spawn.
    - CREATIVE
    - SPECTATOR
  worldBlacklist: #A list of worlds where the clones will not spawn.
    - world1
    - world2
    - world3
  permissions: #If enabled players will only get a clone if they have the permission.
    enabled: false
    permission: 'offlineplayer.clone'
```
etc. (Every bit of information that you might think is relevant in fixing the issue)
    Happens on server restart, player is offline for a long time, despawn timer is off, and everytime i relog
